In [36]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [37]:
df= pd.read_csv(r"C:\Users\User\Desktop\Sales dashboard\restaurant_data_dirty.csv")

print(df.shape)
print(df.columns)

(6120, 20)
Index(['customer_id', 'gender', 'age', 'city', 'signup_date', 'order_id',
       'order_date', 'restaurant_name', 'dish_name', 'category', 'quantity',
       'price', 'payment_method', 'order_frequency', 'last_order_date',
       'loyalty_points', 'churned', 'rating', 'rating_date',
       'delivery_status'],
      dtype='object')

In [38]:
df.head()
df.shape
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6120 entries, 0 to 6119
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      6120 non-null   object
 1   gender           6120 non-null   object
 2   age              6120 non-null   object
 3   city             5996 non-null   object
 4   signup_date      6120 non-null   object
 5   order_id         6120 non-null   object
 6   order_date       6120 non-null   object
 7   restaurant_name  6120 non-null   object
 8   dish_name        6120 non-null   object
 9   category         6120 non-null   object
 10  quantity         4409 non-null   float64
 11  price            5813 non-null   float64
 12  payment_method   6120 non-null   object
 13  order_frequency  6120 non-null   int64
 14  last_order_date  6120 non-null   object
 15  loyalty_points   6120 non-null   int64
 16  churned          6120 non-null   object
 17  rating           5938 non-null   float64
 18  rating_date      6120 non-null   object
 19  delivery_status  6120 non-null   object
dtypes: float64(3), int64(2), object(15)
memory usage: 956.4+ KB

          quantity        price  order_frequency  loyalty_points       rating
count  4409.000000  5813.000000      6120.000000     6120.000000  5938.000000
mean      3.230211   786.402842        25.314216      250.046732     3.021556
std       1.483984   432.774023        14.359091      144.659420     1.450853
min       1.000000 -1484.830000         1.000000        0.000000     0.000000
25%       1.000000   436.080000        13.000000      125.000000     2.000000
50%       3.000000   800.070000        25.000000      249.000000     3.000000
75%       5.000000  1147.650000        37.000000      378.000000     4.000000
max       5.000000  1499.950000        50.000000      500.000000     8.000000

In [39]:
df.tail()

,customer_id,gender,age,city,signup_date,order_id,order_date,restaurant_name,dish_name,category,quantity,price,payment_method,order_frequency,last_order_date,loyalty_points,churned,rating,rating_date,delivery_status
6115,C2143,Other,Teenager,Islamabad,1/16/2025,O6143,4/8/2024,Pizza Hut,Pizza,Italian,4.0,825.88,Card,31,10/9/2024,83,Active,5.0,11/15/2024,Cancelled
6116,C4666,Other,Adult,Lahore,11/9/2023,O8666,10/18/2024,McDonald's,Pasta,Italian,1.0,306.26,Wallet,6,6/21/2025,377,Active,1.0,6/19/2025,Delivered
6117,C5546,Female,Teenager,Islambad,7/2/2025,O9546,6/30/2024,McDonald's,Pasta,Italian,NaN,739.14,Wallet,48,8/22/2024,259,Inactive,4.0,9/7/2024,Cancelled
6118,C2970,Male,Teenager,Lahore,7/1/2024,O6970,9/8/2024,Pizza Hut,Burger,Italian,3.0,1222.86,Cash,35,1/13/2025,9,Active,3.0,4/3/2025,Delivered
6119,C2364,Male,Teenager,Islamabad,1/14/2025,O6364,3/16/2024,Subway,Fries,Italian,4.0,1103.42,Cash,7,3/31/2025,276,Inactive,4.0,3/25/2025,Cancelled

In [40]:
df.isnull().sum()
df.duplicated().sum()
df.nunique()

customer_id        6000
gender                3
age                   3
city                  9
signup_date         730
order_id           6000
order_date          795
restaurant_name       5
dish_name             5
category              9
quantity              4
price              5588
payment_method        9
order_frequency      50
last_order_date     366
loyalty_points      501
churned               2
rating                9
rating_date         366
delivery_status       3
dtype: int64

In [41]:
print(df.dtypes)

customer_id         object
gender              object
age                 object
city                object
signup_date         object
order_id            object
order_date          object
restaurant_name     object
dish_name           object
category            object
quantity           float64
price              float64
payment_method      object
order_frequency      int64
last_order_date     object
loyalty_points       int64
churned             object
rating             float64
rating_date         object
delivery_status     object
dtype: object

In [42]:
print(df.nunique())

customer_id        6000
gender                3
age                   3
city                  9
signup_date         730
order_id           6000
order_date          795
restaurant_name       5
dish_name             5
category              9
quantity              4
price              5588
payment_method        9
order_frequency      50
last_order_date     366
loyalty_points      501
churned               2
rating                9
rating_date         366
delivery_status       3
dtype: int64

In [43]:
df = df.fillna({
    "quantity": df["quantity"].mean(),
    "city": df["city"].mode()[0],
    "rating": df["rating"].median(),
    "price":df["price"].mean()
})
df["category"] = df["category"].str.title()
df = df.drop_duplicates()

In [44]:
df["order_date"] = pd.to_datetime(df["order_date"], errors="coerce")
df["order_date"] = df["order_date"].fillna(df["signup_date"])

In [ ]:
print(df.isnull().sum()[df.isnull().sum() > 0])

In [45]:
df.to_csv("clean_data.csv", index=False)